'use strict';
let content,shownPhotos=[],photoIndex=0,eventMode='upcoming',fullGallery=false;
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{const u=new URL(s,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const icons={rosary:'<ellipse cx="24" cy="20" rx="14" ry="18" stroke-dasharray="1 4" stroke-linecap="round"/><path d="M24 38v20m-5-6h10"/>',sun:'<circle cx="24" cy="23" r="9"/><circle cx="24" cy="23" r="14"/><path d="M24 1v6m0 32v6M2 23h6m32 0h6M8 7l5 5m22 22 5 5M8 39l5-5M35 12l5-5M24 37v20m-10 3h20m-14-3h8"/>',chalice:'<path d="M10 23h28c0 13-5 17-14 17S10 36 10 23Zm14 17v16m-12 4h24m-18-4h12"/><circle cx="24" cy="12" r="9"/><path d="M24 6v12m-5-6h10"/>'};
function icon(name){return '<svg viewBox="0 0 48 64" aria-hidden="true">'+(icons[name]||icons.rosary)+'</svg>'}
function openDialog(d){if(!d.open)d.showModal()}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function isPast(e){return !!(e.endDate||e.date)&&(e.endDate||e.date)<today()}
function renderEvents(mode){eventMode=mode;document.querySelectorAll('[data-events]').forEach(b=>{const on=b.dataset.events===mode;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});let events=content.events.filter(e=>mode==='all'||(mode==='past'?isPast(e):!isPast(e))).sort((a,b)=>mode==='upcoming'?(a.date||'').localeCompare(b.date||''):(b.date||'').localeCompare(a.date||''));$('#event-grid').innerHTML=events.length?events.map(e=>`<article class="event-card ${e.image?'':'no-photo'}">${e.image?`<img class="event-photo" style="${photoStyle(e.image)}" width="800" height="500" src="${escapeHTML(safeUrl(e.image))}" alt="${escapeHTML(e.imageAlt||e.title)}" loading="lazy">`:`<span class="event-category">${escapeHTML(e.category)}</span>`}<div class="event-text"><div class="event-date">${escapeHTML(e.dateLabel||'Data a confirmar')} ${isPast(e)?'· REALIZADO':''}</div><h3>${escapeHTML(e.title)}</h3><p>${escapeHTML(e.description)}</p><button class="button gold" data-event="${escapeHTML(e.id)}">Saiba mais</button></div></article>`).join(''):'<div class="empty-state"><h3>Nosso próximo encontro é com você.</h3><p>Confira a programação semanal enquanto preparamos os próximos avisos.</p><a class="button gold" href="#programacao">Ver programação</a> <button class="button outline-light" id="show-past">Relembre os eventos realizados</button></div>';$('#show-past')?.addEventListener('click',()=>renderEvents('past'));document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{location.hash='evento/'+b.dataset.event})}
function showEvent(id){const e=content.events.find(e=>e.id===id);if(!e)return;$('#detail-content').innerHTML=`<article class="detail-body">${e.image?`<img class="detail-dialog-photo" style="${photoStyle(e.image)}" src="${escapeHTML(safeUrl(e.image))}" alt="${escapeHTML(e.imageAlt||e.title)}">`:''}<p class="eyebrow">${escapeHTML(e.category)}</p><h2>${escapeHTML(e.title)}</h2><p class="event-date">${escapeHTML(e.dateLabel)}${isPast(e)?' · Evento realizado':''}</p><p>${escapeHTML(e.body)}</p><button class="button brown" id="share-event">Compartilhar evento</button>${e.photoNote?`<small>${escapeHTML(e.photoNote)}</small>`:''}</article>`;openDialog($('#detail-dialog'));$('#share-event').onclick=async()=>{const url=new URL('#evento/'+encodeURIComponent(e.id),location.href).href;try{if(navigator.share){await navigator.share({title:e.title,text:e.description,url})}else{await navigator.clipboard.writeText(url);toast('Link do evento copiado.')}}catch(err){if(err.name!=='AbortError'){const a=document.createElement('a');a.href='https://wa.me/?text='+encodeURIComponent(e.title+'\n'+url);a.target='_blank';a.rel='noopener';a.click()}}}}
function galleryFilters(active='Todas'){
 $('#gallery-filters').hidden=!fullGallery;
 $('#gallery-all').textContent=fullGallery?'Recolher galeria':'Ver galeria';
 $('#gallery-filters').innerHTML=['Todas',...content.galleryCategories].map(c=>`<button data-category="${escapeHTML(c)}" class="${c===active?'active':''}" aria-pressed="${c===active}">${escapeHTML(c)}</button>`).join('');
 document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{galleryFilters(b.dataset.category);renderGallery(b.dataset.category)});
}
// Use the full photograph on high-density screens; preserve source bytes.
function photoAttributes(p){
 const thumb=safeUrl(p.thumbnail||p.src),full=safeUrl(p.src);
 return `src="${escapeHTML(thumb)}" ${p.thumbnail?`srcset="${escapeHTML(thumb)} ${p.thumbnailWidth||338}w, ${escapeHTML(full)} ${p.width||865}w" sizes="(max-width:640px) 50vw, (max-width:1150px) 33vw, 25vw"`:''} style="${photoStyle(p.src)}" decoding="async"`;
}
function photoStyle(src){
 const a=content.imageAdjustments?.[src];
 return a?`filter:brightness(${a.brightness}) contrast(${a.contrast}) saturate(${a.saturation})`:'';
}
function renderGallery(category='Todas'){
 if(!fullGallery){
  const covers={'Festa de São Francisco 2025':'1000297410.heic','Missa de despedida do Padre Gilberto':'1000472897.heic'};
  $('#gallery-grid').innerHTML=content.galleryCategories.map(cat=>{const photos=content.gallery.filter(p=>p.category===cat);const p=photos.find(p=>p.original?.endsWith(covers[cat]||'__'))||photos[0];if(!p)return '';return `<button class="gallery-item album-cover" data-album="${escapeHTML(cat)}" aria-label="Abrir álbum: ${escapeHTML(cat)}"><img ${photoAttributes(p)} alt="${escapeHTML(p.alt)}" loading="lazy" width="${p.width||800}" height="${p.height||1000}"><span>${escapeHTML(cat)}<small>${photos.length} fotos</small></span></button>`}).join('');
  $('#gallery-empty').hidden=true;
  document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>{fullGallery=true;galleryFilters(b.dataset.album);renderGallery(b.dataset.album);$('#gallery-filters').scrollIntoView({block:'start',behavior:'smooth'})});return;
 }
 shownPhotos=content.gallery.filter(p=>category==='Todas'||p.category===category);
 let previous='';
 $('#gallery-grid').innerHTML=shownPhotos.map((p,i)=>{const heading=p.category!==previous?`<h3 class="album-heading">${escapeHTML(p.category)}</h3>`:'';previous=p.category;return heading+`<button class="gallery-item" data-photo="${i}" aria-label="Ampliar: ${escapeHTML(p.title)}"><img ${photoAttributes(p)} alt="${escapeHTML(p.alt)}" loading="lazy" width="${p.width||800}" height="${p.height||1000}"><span>${escapeHTML(p.title)}</span></button>`}).join('');
 $('#gallery-empty').hidden=!!shownPhotos.length;
 document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{photoIndex=Number(b.dataset.photo);updatePhoto();openDialog($('#lightbox'))});
}
function updatePhoto(){const p=shownPhotos[photoIndex];$('#lightbox-img').src=p.src;$('#lightbox-img').style.cssText=photoStyle(p.src);$('#lightbox-img').alt=p.alt;$('#lightbox-caption').textContent=p.title;$('#photo-original').href=safeUrl(p.original||p.src);$('#photo-original').download=(p.original||p.src).split('/').pop();$('#photo-count').textContent=(photoIndex+1)+' / '+shownPhotos.length}
function movePhoto(n){if(shownPhotos.length){photoIndex=(photoIndex+n+shownPhotos.length)%shownPhotos.length;updatePhoto()}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
function route(){if(content&&location.hash.startsWith('#evento/'))showEvent(decodeURIComponent(location.hash.slice(8)))}
async function init(){try{const response=await fetch('content.json?v=20261003-cor2');if(!response.ok)throw Error('Content');content=await response.json();$('#schedule').innerHTML=content.schedule.map(s=>`<article class="schedule-card">${icon(s.icon)}<div><h3>${escapeHTML(s.title)}</h3><p>${escapeHTML(s.day)}</p><strong>${escapeHTML(s.time)}</strong></div></article>`).join('');$('.hero-photo').src=content.heroImage;$('#about-photo').src=content.aboutImage;document.querySelectorAll('.hero-photo,#about-photo,.location-photo,.hero-note img').forEach(img=>{const src=img.getAttribute('src');img.style.cssText=photoStyle(src)});$('#about-text').textContent=content.aboutText;
$('#address-text').textContent=content.address;$('#header-whatsapp').href='https://wa.me/'+content.phone;$('#phone-link').href='tel:+'+content.phone;$('#phone-link').textContent=content.phoneLabel;$('#email-link').href='mailto:'+content.email;$('#email-link').textContent=content.email;$('#maps-link').href=content.mapUrl||('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(content.mapQuery));$('#map').src='https://maps.google.com/maps?q='+encodeURIComponent(content.mapQuery)+'&output=embed';$('#whatsapp-link').href='https://wa.me/'+content.phone;$('#socials').innerHTML=Object.entries(content.social).filter(([k,v])=>v&&safeUrl(v)).map(([k,v])=>`<a href="${escapeHTML(safeUrl(v))}" target="_blank" rel="noopener">${escapeHTML(k[0].toUpperCase()+k.slice(1))}</a>`).join('');$('#logos').innerHTML=content.logos.filter(l=>l.src).map(l=>`<img src="${escapeHTML(safeUrl(l.src))}" alt="${escapeHTML(l.name)}" loading="lazy" width="240" height="105">`).join('');renderEvents(content.events.some(e=>!isPast(e))?'upcoming':'past');renderGallery();route();
$('#history-open').onclick=()=>{$('#detail-content').innerHTML='<article class="detail-body"><p class="eyebrow">NOSSA HISTÓRIA</p><h2>30 anos caminhando juntos.</h2>'+content.history.map(p=>'<p>'+escapeHTML(p)+'</p>').join('')+'<a class="button brown" id="history-contact" href="#contato">Faça parte dessa caminhada</a></article>';openDialog($('#detail-dialog'));$('#history-contact').onclick=()=>$('#detail-dialog').close()};
$('#anniversary-open').onclick=()=>$('#history-open').click();
$('#contact-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target);const message='Olá! Meu nome é '+form.get('name')+'.\nAssunto: '+form.get('subject')+'\n\n'+form.get('message');window.open('https://wa.me/'+content.phone+'?text='+encodeURIComponent(message),'_blank','noopener')};
$('#gallery-all').onclick=()=>{fullGallery=!fullGallery;galleryFilters();renderGallery()};
}catch(err){$('#schedule').innerHTML='<p>Não foi possível carregar as informações. <a href="https://wa.me/5547999960210">Fale com a comunidade pelo WhatsApp.</a></p>';console.error(err)}}
$('.menu-toggle').onclick=()=>{const open=$('#nav').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',open);$('.menu-toggle').setAttribute('aria-label',open?'Fechar menu':'Abrir menu');$('.menu-toggle').textContent=open?'×':'☰'};$('#nav').querySelectorAll('a').forEach(a=>a.onclick=()=>{$('#nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').textContent='☰'});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#nav').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').textContent='☰'}if($('#lightbox').open){if(e.key==='ArrowLeft')movePhoto(-1);if(e.key==='ArrowRight')movePhoto(1)}});document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$('#detail-dialog').addEventListener('close',()=>{if(location.hash.startsWith('#evento/'))history.replaceState(null,'','#eventos')});$('#photo-prev').onclick=()=>movePhoto(-1);$('#photo-next').onclick=()=>movePhoto(1);let touchX=0;$('#lightbox-img').addEventListener('touchstart',e=>touchX=e.changedTouches[0].screenX,{passive:true});$('#lightbox-img').addEventListener('touchend',e=>{const delta=e.changedTouches[0].screenX-touchX;if(Math.abs(delta)>50)movePhoto(delta<0?1:-1)},{passive:true});document.querySelectorAll('[data-events]').forEach(b=>b.onclick=()=>renderEvents(b.dataset.events));$('#events-all').onclick=()=>renderEvents('all');window.addEventListener('hashchange',route);init();
